server:
  port: 8083

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://c-c9qikb36ojt5s6c7vpfo.rw.mdb.yandexcloud.net:6432/tsypk?currentSchema=dev
    username: tsypk
    password: 15.Aleksei
    max-active: 2

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        buy_request_channel:
          name: buy_request_channel
        stuff_update_channel:
          name: stuff_update_channel
